#!/bin/sh
mdev -s
mkdir /tmp /disk
chmod 777 /tmp
sh /scripts/prepdriver.sh
mdev -s

if [ -b /dev/sda2 ]
then
  ntfs-3g /dev/sda2 /disk -o rw,noatime
else
  ntfs-3g /dev/sda1 /disk -o rw,noatime
fi

if [ -d /disk/WINDOWS ]
then
  reged -IC /disk/WINDOWS/system32/config/system HKEY_LOCAL_MACHINE\\SYSTEM /scripts/xp.reg
else
  reged -IC /disk/Windows/System32/config/SOFTWARE HKEY_LOCAL_MACHINE\\SOFTWARE /scripts/deuac.reg
fi
umount /disk 2>/dev/null
poweroff
